# Generated by Django 5.0.4 on 2024-04-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('from_location', models.TextField()),
                ('to_location', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
