# Generated by Django 5.0.4 on 2024-04-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactus',
        ),
    ]
